import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
    return (
        <div>
            <Layout>
                <Head>
                <title>FUDO</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Logo.png" />
                </Head>
                {/* body */}
                <main>
                <h1>Subscribe Zainkeepscode</h1>
                </main>
            </Layout>
        </div>
    );
}

